version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn mysite.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mysite_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GODISGREAT2all!
    ports:
      - "5000:5432"